### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by IronSloth** [chrisseroka/ps-menu#11]
It might be a good idea to include more documentation and examples on how to setup the menus, minus the .gifs.

**Comment by eabase** [comment]
Yep, what does the `$Multiselect`do? 
It doesn't seem to do anything...

**Comment by chrisseroka** [comment]
> Yep, what does the `$Multiselect`do? It doesn't seem to do anything...

It allows to select more than 1 option, e.g.:
![image](https://github.com/chrisseroka/ps-menu/assets/434563/78a5d6a5-014e-4965-bb7d-ee857f09e09a)
