### ISSUE TITLE
`ESC` to quit the menu misplaces the next prompt

### ISSUE THREAD

**Issue by mklement0** [chrisseroka/ps-menu#13]
When you press <kbd>Esc</kbd> to exit a menu, the subsequent prompt doesn't appear _below_ the menu that was just displayed, but seemingly _on the line of  the statement that originally invoked the menu or some other line above_, while leaving lines below intact, making for a confusing visual experience.

**Comment by jasonrush** [comment]
I saw a similar issue when I had just manually added the functions to my session. After I started a new session and installed via `Install-Module PS-Menu`, it seems to be working as expected and I'm no longer able to reproduce the issue.

**Comment by mklement0** [comment]
I still see the symptom (just reinstalled), but it only appears _if the selection has never been moved with the arrow keys_ before pressing <kbd>ESC</kbd>.

**Comment by jasonrush** [comment]
In my initial testing, I had created three options, and the last option seemed like it was working normally, but the first two were having issues. Just to add a bit more detail.

**Comment by mklement0** [comment]
Invoke the following:

```
menu (1..3)
```

Then, _without having moved the selection_, press <kbd>ESC</kbd> - you'll see the symptom.

Then clear the screen and re-invoke the command above.

Move the selection - regardless of where, possibly even back to the _first_ item - and _then_ press <kbd>ESC</kbd> - you will _not_ see the symptom.

Let me know if you see something different.

**Comment by jasonrush** [comment]
So with it installed properly via `Install-Module PS-Menu`, running `menu (1..3)` and then pressing esc w/o moving, it ended up overwriting the line for option 3.
![image](https://github.com/chrisseroka/ps-menu/assets/510971/e91b7099-29e1-403a-b15e-fc4464654220)
Without clearing the screen, I tried the very same test and it actually took me back to the previous line where I had invoked menu from.
![image](https://github.com/chrisseroka/ps-menu/assets/510971/d6cd862a-d6e0-49c4-b471-482b9d908fb5)
I tried clearing, then adding multiple newlines just to get it off of the top of the terminal, and had the same result as my last test above (took me back to my last prompt line).
![image](https://github.com/chrisseroka/ps-menu/assets/510971/f3a9c639-4acd-4324-9086-8ffba9c08546)

**Comment by jasonrush** [comment]
This may or may not be related. If I run the module code directly (instead of importing it as a module), I see the same results as above but *also* get the following error only when the "haven't pressed anything, then press esc" situation happens.
![image](https://github.com/chrisseroka/ps-menu/assets/510971/06559afe-6bd1-4ff3-9802-e8b5f54a1373)

**Comment by mklement0** [comment]
Sounds good; to summarize: 

* Never having moved the selection before pressing <kbd>Esc</kbd> is the buggy code path, though the symptoms vary depending on whether the active terminal line was the first one at the time of the `menu` call.

* The likely culprit is the lack of _unconditional_ initialization of the `$startPos` variable:

  * https://github.com/chrisseroka/ps-menu/blob/68dfd70c0022b3746996a5459ae6af83ca5491ce/ps-menu.psm1#L44-L69

* Placing `$startPos = [System.Console]::CursorTop` as the first statement inside the `try` statement above seems to fix the problem.
