### ISSUE TITLE
Feature:  Add .. and possibility to keep menu after having selected new directory

### ISSUE THREAD

**Issue by eabase** [chrisseroka/ps-menu#18]
Potential new improvements. 

Add:
1. Being able to go back/up in directory (as done by `..`).
2. After selecting a direcroy, keep menu alive with new directories.  
   Hitting `Return` 2x exits in that current one.

**Comment by chrisseroka** [comment]
The goal of this module is to provide a simple way to generate "menus" in Powershell - directory navigation is just a simple examples, not part of this module.
