### ISSUE TITLE
Does not erase choices on keypress

### ISSUE THREAD

**Issue by kiedtl** [chrisseroka/ps-menu#5]
See image:

![image](https://user-images.githubusercontent.com/32681240/56172286-cb3d7580-5fb6-11e9-985b-52449209321f.png)

**Comment by cspotcode** [comment]
I explain the problem here: Sebazzz/PSMenu#1

**Comment by kiedtl** [comment]
Yep, thats definitely the problem. Hope the PR is merged.

**Comment by kort3x** [comment]
still broken

**Comment by chrisseroka** [comment]
Thanks for reporting that. The issue has been fixed in 1.0.7. Please update your module.
